### ISSUE TITLE
New styles to contribute

### ISSUE THREAD

**Issue by vanukalla** [JabRef/jstyles.jabref.org#1]
I created 3 new sytlefiles that I want to contribute. Since uploading did not work, I am pasting the styles below. They worked perfectly for me except that the reference lists need some final editing (I have not found a solution, yet, for the numbered reference format). Suggestions are welcome! 

1) **Blood**

# This file is licensed under the terms of CC BY 4.0. 
# Written by Katrina Vanura, Medical University of Vienna, AUT

NAME
Blood style file

JOURNALS
Blood

PROPERTIES
Title="References"
IsSortByPosition=true
IsNumberEntries=true
ReferenceParagraphFormat="Standard"
ReferenceHeaderParagraphFormat="Heading 1"

CITATION
MaxAuthors=6
MaxAuthorsFirst=6
AuthorSeparator=", "
AuthorLastSeparator=", "
EtAlString=" et al"
ItalicEtAl="true"
CitationSeparator=","
MultiCiteChronological=true
BracketBefore=""
BracketAfter=""
BracketBeforeInList=""
BracketAfterInList=""
MinimumGroupingCount=3
CitationCharacterFormat="Standard"
FormatCitations=true
GroupedNumbersSeparator="-"
UniquefierSeparator=","
InTextYearSeparator=" "
YearSeparator=" "

LAYOUT
article=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}<i>\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}</i>.\begin{year} \year\uniq;\end{year}\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]{\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

book=\begin{editor}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al.,6,6),]{\editor}\end{editor} \begin{title} \format[RemoveLatexCommands]{\title} \end{title} \address: \publisher; \year\uniq.

inbook=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}In: \begin{editor} \format[RemoveLatexCommands]\format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al.,6,6),]{\editor} eds.\end{editor} \begin{booktitle} \format[RemoveLatexCommands]{\booktitle}\end{booktitle}\address: \publisher; \year\uniq:\begin{pages} \format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages} 

default=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}<i>\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}</i>.\begin{year} \year\uniq;\end{year}\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]{\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

2) **Haematologica**

# This file is licensed under the terms of CC BY 4.0. 
# Written by Katrina Vanura, Medical University of Vienna, AUT

NAME
Haematologica style file

JOURNALS
Haematologica

PROPERTIES
Title="References"
IsSortByPosition=true
IsNumberEntries=true
ReferenceParagraphFormat="Standard"
ReferenceHeaderParagraphFormat="Heading 1"

CITATION
MaxAuthors=6
MaxAuthorsFirst=6
AuthorSeparator=", "
AuthorLastSeparator=", "
EtAlString=" et al"
ItalicEtAl="true"
CitationSeparator=","
MultiCiteChronological=true
BracketBefore=""
BracketAfter=""
BracketBeforeInList=""
BracketAfterInList=""
MinimumGroupingCount=3
CitationCharacterFormat="Standard"
FormatCitations=true
GroupedNumbersSeparator="-"
UniquefierSeparator=","
InTextYearSeparator=" "
YearSeparator=" "

LAYOUT
article=\begin{author}. \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}<i>\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}</i>.\begin{year} \year\uniq;\end{year}\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]{\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

book=\begin{editor}. \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\editor}\end{editor} eds.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}\address: \publisher; \year\uniq. 

inbook=\begin{author}. \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}In:\begin{booktitle} \format[RemoveLatexCommands]{\booktitle}\end{booktitle} \address: \publisher; \year\uniq. p. \begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}

default=\begin{author}. \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}<i>\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}</i>.\begin{year} \year\uniq;\end{year}\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]{\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

3)**Leukemia**

# This file is licensed under the terms of CC BY 4.0. 
# Written by Katrina Vanura, Medical University of Vienna, AUT

NAME
Leukemia style file

JOURNALS
Leukemia

PROPERTIES
Title="References"
IsSortByPosition=true
IsNumberEntries=true
ReferenceParagraphFormat="Standard"
ReferenceHeaderParagraphFormat="Heading 1"

CITATION
MaxAuthors=6
MaxAuthorsFirst=6
AuthorSeparator=", "
AuthorLastSeparator=", "
EtAlString=" et al"
ItalicEtAl="true"
CitationSeparator=","
MultiCiteChronological=true
BracketBefore=""
BracketAfter=""
BracketBeforeInList=""
BracketAfterInList=""
MinimumGroupingCount=3
CitationCharacterFormat="Standard"
FormatCitations=true
GroupedNumbersSeparator="-"
UniquefierSeparator=","
InTextYearSeparator=" "
YearSeparator=" "

LAYOUT
article=\begin{author} \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}<i>\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}</i>\begin{year} \year\uniq;\end{year}<b>\begin{volume} \format[RemoveLatexCommands]{\volume}\end{volume}</b>:\begin{pages} \format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

book=\begin{editor} \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al.,6,6),]{\editor}\end{editor} (eds).<i>\begin{title} \format[RemoveLatexCommands]{\title}\end{title}</i> \publisher: \address, \year\uniq.

inbook=\begin{author} \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}In: \begin{editor} \format[RemoveLatexCommands] \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al.,6,6),]{\editor} (eds).\end{editor}<i>\begin{booktitle} \format[RemoveLatexCommands]{\booktitle}\end{booktitle}</i> \publisher: \address, \year\uniq, pp \begin{pages} \format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}

default=\begin{author} \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}<i>\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}</i>\begin{year} \year\uniq;\end{year}<b>\begin{volume} \format[RemoveLatexCommands]{\volume}\end{volume}</b>:\begin{pages} \format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

**Comment by koppor** [comment]
Would you mind trying to click on "Create new File"? Maybe, that did not work? If not, I will try to reach you next week on the phone, if that is OK for you.

![grafik](https://user-images.githubusercontent.com/1366654/37849614-a7875daa-2ed8-11e8-8b71-52dcc0d388cb.png)

**Comment by vanukalla** [comment]
I added  1 file to see how it works and got a little lost in the process. I will try another one later on, at some point I'll get the hang of it....

**Comment by vanukalla** [comment]
I have not figured out how to add the information to the readme.md. Or will you do that?

**Comment by koppor** [comment]
Both https://github.com/JabRef/jstyles.jabref.org/pull/3 and https://github.com/JabRef/jstyles.jabref.org/pull/4 look good!

You can just click the pencil at the README.md and add text. With images, it is harder to do.

![grafik](https://user-images.githubusercontent.com/1366654/37901728-7c765a28-30f2-11e8-8b00-a9547c945372.png)

When the support for [CitationStyles.org](http://citationstyles.org/) comes into the OO-Integration (see https://github.com/JabRef/jabref/issues/2146), would you still use the jstyles?

**Comment by vanukalla** [comment]
To be frank - I simply don't know whether I would switch to CSL or still use jstyles. I would have to try how the handling is within jabref. I am quite happy with how things are working right now - after I got the hang of modifying the style files. :-)

**Comment by koppor** [comment]
Thank you for your contributions. They are now online at https://jstyles.jabref.org.
