### ISSUE TITLE
More stylefiles for hematological journals

### ISSUE THREAD

**Issue by vanukalla** [JabRef/jstyles.jabref.org#2]
**1. American Journal of Hematology**

# This file is licensed under the terms of CC BY 4.0. 
# Written by Katrina Vanura, Medical University of Vienna, AUT

NAME
Am J Hematol style file

JOURNALS
American Journal of Hematology

PROPERTIES
Title="References"
IsSortByPosition=true
IsNumberEntries=true
ReferenceParagraphFormat="Standard"
ReferenceHeaderParagraphFormat="Heading 1"

CITATION
AuthorSeparator=", "
AuthorLastSeparator=", "
EtAlString=" et al"
ItalicEtAl="true"
CitationSeparator=","
MultiCiteChronological=true
BracketBefore=""
BracketAfter=""
BracketBeforeInList=""
BracketAfterInList=""
MinimumGroupingCount=3
CitationCharacterFormat="Standard"
FormatCitations=true
GroupedNumbersSeparator="-"
UniquefierSeparator=","
InTextYearSeparator=" "
YearSeparator=" "

LAYOUT
article=\begin{author} \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title}\end{title} <i>\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}</i>.\begin{year} \year\uniq;\end{year}\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]({\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

book=\begin{editor} \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ),]{\editor}\end{editor} (eds).\begin{title} \format[RemoveLatexCommands]{\title}\end{title} \address: \publisher; \year\uniq.\begin{pages} \format[RemoveLatexCommands,FormatPagesForHTML,LastPage]{\pages} p.\end{pages}

inbook=\begin{author} \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}In: \begin{editor} \format[RemoveLatexCommands] \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al.,6,6),]{\editor} (eds).\end{editor}\begin{booktitle} \format[RemoveLatexCommands]{\booktitle}\end{booktitle} \address: \publisher; \year\uniq.\begin{pages} \format[RemoveLatexCommands,FormatPagesForHTML,LastPage]{\pages} p.\end{pages}

default=\begin{author} \format[Authors(LastFirst,InitialsNospace,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}<i>\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}</i>\begin{year} \year\uniq;\end{year}<b>\begin{volume} \format[RemoveLatexCommands]{\volume}\end{volume}</b>:\begin{pages} \format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

**2. Annals of Hematology**

# This file is licensed under the terms of CC BY 4.0. 
# Written by Katrina Vanura, Medical University of Vienna, AUT

NAME
Ann Hematol style file

JOURNALS
Annals of Hematology

PROPERTIES
Title="References"
IsSortByPosition=true
IsNumberEntries=true
ReferenceParagraphFormat="Standard"
ReferenceHeaderParagraphFormat="Heading 1"

CITATION
MaxAuthors=15
MaxAuthorsFirst=15
AuthorSeparator=", "
AuthorLastSeparator=", "
EtAlString=" et al"
ItalicEtAl="true"
CitationSeparator=", "
MultiCiteChronological=true
BracketBefore="["
BracketAfter="]"
BracketBeforeInList=""
BracketAfterInList=""
MinimumGroupingCount=3
CitationCharacterFormat="Standard"
FormatCitations=true
GroupedNumbersSeparator="-"
UniquefierSeparator=","
InTextYearSeparator=" "
YearSeparator=" "

LAYOUT
article=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,15,15)]{\author}\end{author}\begin{year} (\year\uniq)\end{year}\begin{title} \format[RemoveLatexCommands]{\title} \end{title}\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal} \begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]{\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

book=\begin{editor}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al.,15,15)]{\editor}\end{editor} \begin{year}(\year\uniq)\end{year}\begin{title} \format[RemoveLatexCommands]{\title} \end{title} \publisher, \address. 

inbook=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,15,15)]{\author}\end{author} (\year\uniq)\begin{title} \format[RemoveLatexCommands]{\title} \end{title}In: \begin{editor}\format[RemoveLatexCommands]\format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al.,15,15)]{\editor} (eds)\end{editor} \begin{booktitle}\format[RemoveLatexCommands]{\booktitle}\end{booktitle} \publisher, \address, \begin{pages}pp \format[RemoveLatexCommands,FormatPagesForHTML]{\pages}\end{pages} 

default=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,15,15),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}.\begin{year} \year\uniq;\end{year}\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]{\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

**3. British Journal of Haematology**

# This file is licensed under the terms of CC BY 4.0. 
# Written by Katrina Vanura, Medical University of Vienna, AUT

NAME
Journal names need to be in unabbreviated format in Jabref.
In group citation only the first et al in italics, other et al need to be formatted.
Br J Haematol style file

JOURNALS
British Journal of Haematology

PROPERTIES
Title="References"
IsSortByPosition=false
IsNumberEntries=false
ReferenceParagraphFormat="EndNote Bibliography"
ReferenceHeaderParagraphFormat="EndNote Bibliography Title"

CITATION
AuthorField=author/editor
YearField="year"
MaxAuthors=2
AuthorLastSeparator=" & "
EtAlString=" et al"
ItalicEtAl="true"
CitationSeparator="; "
MultiCiteChronological="true"
BracketBefore="("
BracketAfter=")"
CitationCharacterFormat="Default Style"
FormatCitations="true"
UniquefierSeparator=", "
InTextYearSeparator=" "
YearSeparator=", "

LAYOUT
article=\begin{author}\format[Authors(LastFirst,InitialsNospace,sep=\, ,LastSep= & ),]{\author}\end{author} (\begin{year}\year\uniq\end{year})\begin{title} \format[RemoveLatexCommands]{\title} \end{title}<i>\begin{journal}\format[RemoveLatexCommands]{\journal}\end{journal}</i>, <b>\begin{volume}\format[RemoveLatexCommands]{\volume},\end{volume}</b> \begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

book=\begin{editor}\format[Authors(LastFirst,InitialsNospace,sep=\, ,LastSep= & ),]{\editor}\end{editor} (\year\uniq)\begin{title} \format[RemoveLatexCommands]{\title} \end{title}\address: \publisher. 

inbook=\begin{author}\format[Authors(LastFirst,InitialsNospace,sep=\, ,LastSep= & ),]{\author}\end{author} (\year\uniq)\begin{title} \format[RemoveLatexCommands]{\title}\end{title} In:\begin{editor} \format[RemoveLatexCommands]\format[Authors(LastFirst,InitialsNospace,sep=\, ,LastSep= & ),]{\editor} eds.\end{editor} (\year\uniq)\begin{booktitle} \format[RemoveLatexCommands]{\booktitle}\end{booktitle}\address: \publisher, \begin{pages} \format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages} 

default=\begin{author}\format[Authors(LastFirst,InitialsNospace,sep=\, ,LastSep= & ),]{\author}\end{author} (\begin{year} \year\uniq;\end{year}) \begin{title} \format[RemoveLatexCommands]{\title} \end{title}<i>\begin{journal}\format[RemoveLatexCommands]{\journal}\end{journal}</i>, <b>\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}</b>, \begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

**4. Hematological Oncology**

# This file is licensed under the terms of CC BY 4.0. 
# Written by Katrina Vanura, Medical University of Vienna, AUT

NAME
Hematol Oncol style file

JOURNALS
Hematological Oncology

PROPERTIES
Title="References"
IsSortByPosition=true
IsNumberEntries=true
ReferenceParagraphFormat="Standard"
ReferenceHeaderParagraphFormat="Heading 1"

CITATION
MaxAuthors=6
MaxAuthorsFirst=6
AuthorSeparator=", "
AuthorLastSeparator=", "
EtAlString=" et al"
ItalicEtAl="false"
CitationSeparator=","
MultiCiteChronological=true
BracketBefore=""
BracketAfter=""
BracketBeforeInList=""
BracketAfterInList=""
MinimumGroupingCount=3
CitationCharacterFormat="Standard"
FormatCitations=true
GroupedNumbersSeparator="-"
UniquefierSeparator=","
InTextYearSeparator=" "
YearSeparator=" "

LAYOUT
article=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl=\, et al,6,6)]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}.\begin{year} \year\uniq;\end{year}\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]{\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

book=\begin{editor}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl=\, et al.,6,6),]{\editor}\end{editor} \begin{title} \format[RemoveLatexCommands]{\title} \end{title} \address: \publisher; \year\uniq.

inbook=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl=\, et al,6,6),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}In: \begin{editor} \format[RemoveLatexCommands]\format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al.,6,6),]{\editor} eds.\end{editor} \begin{booktitle} \format[RemoveLatexCommands]{\booktitle}\end{booktitle}\address: \publisher; \year\uniq:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages} 

default=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,15,15),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}.\begin{year} \year\uniq;\end{year}\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]{\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

**5. Journal of Hematology and Oncology**

# This file is licensed under the terms of CC BY 4.0. 
# Written by Katrina Vanura, Medical University of Vienna, AUT

NAME
J Hematol Oncol style file

JOURNALS
Journal of Hematology and Oncology

PROPERTIES
Title="References"
IsSortByPosition=true
IsNumberEntries=true
ReferenceParagraphFormat="Standard"
ReferenceHeaderParagraphFormat="Heading 1"

CITATION
MaxAuthors=15
MaxAuthorsFirst=15
AuthorSeparator=", "
AuthorLastSeparator=", "
EtAlString=" et al"
ItalicEtAl="true"
CitationSeparator=", "
MultiCiteChronological=true
BracketBefore="["
BracketAfter="]"
BracketBeforeInList=""
BracketAfterInList=""
MinimumGroupingCount=3
CitationCharacterFormat="Standard"
FormatCitations=true
GroupedNumbersSeparator="-"
UniquefierSeparator=","
InTextYearSeparator=" "
YearSeparator=" "

LAYOUT
article=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,15,15),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}.\begin{year} \year\uniq;\end{year}\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]{\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

book=\begin{editor}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al.,15,15),]{\editor}\end{editor} \begin{title} \format[RemoveLatexCommands]{\title} \end{title} \address: \publisher; \year\uniq.

inbook=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,15,15),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}In: \begin{editor} \format[RemoveLatexCommands]\format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al.,15,15),]{\editor} eds.\end{editor} \begin{booktitle} \format[RemoveLatexCommands]{\booktitle}\end{booktitle}\address: \publisher; \year\uniq:\begin{pages} \format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages} 

default=\begin{author}. \format[Authors(LastFirst,FirstInitial,NoPunc,sep=\, ,LastSep=\, ,EtAl= et al,15,15),]{\author}\end{author}.\begin{title} \format[RemoveLatexCommands]{\title} \end{title}\begin{journal}\format[JournalAbbreviator]{\journal}\end{journal}.\begin{year} \year\uniq;\end{year}\begin{volume}\format[RemoveLatexCommands]{\volume}\end{volume}\begin{number}(\format[RemoveLatexCommands]{\number})\end{number}:\begin{pages}\format[RemoveLatexCommands,FormatPagesForHTML]{\pages}.\end{pages}<br>

**Comment by koppor** [comment]
Online at https://jstyles.jabref.org.
